# =====================================================
# Copyright 2023 Focason Co.,Ltd. AllRights Reserved.
# =====================================================
version: "3.8"

services:

  api-server:
    image: focason-api:latest
    container_name: focason-api_container
    environment:
      APP_PORT: 80
      DB_HOST: mysql.focason.com
      DB_PORT: 3306
      DB_NAME: focason
      DB_USERNAME: root
      DB_PASSWORD: password
    ports:
      - "8080:80"
#    depends_on:
#      - mysql-server
    restart: on-failure
#
#  mysql-server:
#    image: mysql:5.7
#    container_name: focason-db_container
#    environment:
#      MYSQL_DATABASE: focason
#      MYSQL_USER: root
#      MYSQL_PASSWORD: password
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_SCHEMA: focason
#      TZ: 'Asia/Tokyo'
#    ports:
#      - "33061:33061"
#    healthcheck:
#      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
#      start_period: 10s
#      interval: 1s
#      timeout: 1s
#      retries: 10
#    restart: on-failure
