version: "3"

services:
  api:
    image: lemonico-api:latest
    container_name: lemonico-api-container
    ports:
      - 8080:8080
    environment:
      MYSQL_DATABASE: lemonico
      MYSQL_USER: root
      MYSQL_PASSWORD: kawasemi
      MYSQL_ROOT_PASSWORD: kawasemi
    links:
      - db
    depends_on:
      - db

  db:
    image: lemonico-mysql:latest
    container_name: lemonico-mysql-container
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    volumes:
#      - ./mysql/sql:/docker-entrypoint-initdb.d
#      - ./mysql/settings:/var/lib/mysql
    environment:
      MYSQL_DATABASE: horizon
      MYSQL_USER: root
      MYSQL_PASSWORD: kawasemi
      MYSQL_ROOT_PASSWORD: kawasemi
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306