openapi: '3.0.0'
info:
  version: '0.0.1'
  title: 'Blazeash API'
  description: Order Management System designed by Yuan.
  contact: 
    name: Yuan
    email: yuanmz9432@gmail.com
servers: [
  {
    url: https://api-stg.lemonico.com/api
  },
  {
    url: https://api.lemonico.com/api
  }
]
tags:
  - name: Commons
    description: 共通API
paths:
  /heartbeat:
    get:
      summary: For AWS target group health check.
      responses:
        '204':
          description: No content.
        '500':
          description: Unexpected error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /login:
    post:
      operationId: login
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/UserResource'
      responses:
        '200':
          description: 'success'
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: access token.
                  expires_in:
                    type: integer
                    description: Validity period of access token.
        
components:
  schemas:
    UserResource:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          description: the name of user.
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []