spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lemonico?useSSL=false&autoReconnect=true
    username: root
    password: kawasemi
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: Asia/Tokyo

server:
  port: 8080

logging: 
  level:
    root: INFO
    api.lemonico: TRACE

jwt:
  secret: iWpJnu21sTumTsfy
  access_token_expires_in: 3600
  refresh_token_expires_in: 604800
  access_token_header: X-ACCESS-TOKEN
  refresh_token_header: X-REFRESH-TOKEN
