spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lemonico?useSSL=false&autoReconnect=true
    username: root
    password: kawasemi
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8080

doma:
  dialect: mysql
  
logging: 
  level:
    root: INFO
    co.jp.geekfun.horizon: TRACE
