spring:
  profiles:
    active: develop #develop #honban #staging
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

doma:
  dialect: mysql

server:
  servlet:
    context-path: /api
