# Spring Bootフレームワーク
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_SCHAME:lemonico}?useSSL=false&autoReconnect=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:kawasemi}
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: Asia/Tokyo

# Doma
doma:
  dialect: mysql

# サーバー
server:
  servlet:
    context-path: /api
  port: ${APP_PORT:8081}

# ログ
logging:
  level:
    root: WARN
    api.lemonico: INFO

# JWTトークン
jwt:
  secret: ${APP_SECRET:iWpJnu21sTumTsfyldkfjpo23iiu34tierfjwerjfop43oeorgfsndhfopoewkrjti43orweksdnfjw4e}
  access_token_expires_in: 3600 # 単位：秒
  refresh_token_expires_in: 604800 # 単位：秒
  access_token_header: X-ACCESS-TOKEN
  refresh_token_header: X-REFRESH-TOKEN

# AWS
cloud:
  aws:
    region: 'ap-northeast-1'
    s3:
      file-upload:
        bucket-name: lemonico-file
        prefix:
        pre-signed-url-valid-minutes: 15
