spring:
  datasource:
    url: jdbc:mysql://lemonico.crwkn7mkbqkv.ap-northeast-1.rds.amazonaws.com:3306/lemonico?useSSL=false&autoReconnect=true
    username: admin
    password: password
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 80

logging:
  level:
    root: INFO

cloud:
  aws:
    region: 'ap-northeast-1'
    s3:
      item-upload:
        bucket-name: s3-lemonico-upload-sandbox
        prefix: items
        pre-signed-url-valid-minutes: 15

jwt:
  secret: iWpJnu21sTumTsfy
  access_token_expires_in: 600
  refresh_token_expires_in: 604800
  access_token_header: X-ACCESS-TOKEN
  refresh_token_header: X-REFRESH-TOKEN