spring:
  datasource:
    url: jdbc:mysql://dev-horizon-rds-instance-1a.cpf924jlgmcd.ap-northeast-1.rds.amazonaws.com:3306/horizon?useSSL=false&autoReconnect=true
    username: admin
    password: password
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 80

doma:
  dialect: mysql
  
logging: 
  level:
    root: INFO
    co.jp.geekfun.horizon: TRACE
