# =====================================================
# Copyright 2021 Lemonico Co.,Ltd. AllRights Reserved.
# =====================================================
version: "3.8"

services:

  app:
    image: lemonico-api:latest
    container_name: lemonico-api_app
    environment:
      DB_HOST: dbserver
      DB_PORT: 3306
      DB_NAME: lemonico
      DB_USERNAME: root
      DB_PASSWORD: kawasemi
    ports:
      - 8080:8080
    depends_on:
      - dbserver
    restart: on-failure

  dbserver:
    image: lemonico-mysql:latest
    container_name: lemonico-api_dbserver
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lemonico
      MYSQL_USER: yuan
      MYSQL_PASSWORD: kawasemi
      MYSQL_ROOT_PASSWORD: kawasemi
      MYSQL_SCHEMA: kawasemi
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    healthcheck:
      test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
      start_period: 10s
      interval: 1s
      timeout: 1s
      retries: 10
    restart: on-failure
