-- MySQL Script generated by MySQL Workbench
-- Sat Oct 16 11:51:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='';

DROP database IF EXISTS `lemonico`;
CREATE DATABASE `lemonico`;

-- -----------------------------------------------------
-- Table `lemonico`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lemonico`.`user` ;

CREATE TABLE IF NOT EXISTS `lemonico`.`user` (
    `id` INT NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
    `first_name` VARCHAR(255) NOT NULL COMMENT '姓',
    `last_name` VARCHAR(255) NULL COMMENT '名',
    `email` VARCHAR(255) NOT NULL COMMENT 'メールアドレス',
    `password` VARCHAR(255) NOT NULL COMMENT 'パスワード',
    `status` INT NOT NULL DEFAULT 1 COMMENT 'ステータス（1:通常 2:ブラックユーザー 3:退会）',
    `created_by` VARCHAR(255) NOT NULL COMMENT '作成者',
    `created_at` DATETIME NOT NULL COMMENT '作成日時',
    `modified_by` VARCHAR(255) NOT NULL COMMENT '更新者',
    `modified_at` DATETIME NOT NULL COMMENT '更新日時',
    `is_deleted` INT NOT NULL DEFAULT 0 COMMENT '削除フラグ（退会から一定時間経過後に削除状態になる）',
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COMMENT = 'ユーザー';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
